### PR TITLE
cleaning up kyber master for stable

### LINKED ISSUE #221: Pass master-build
For the moment the build in master doesn't pass because of the `experimental`-branch. I started to add a `experimantal/abstract` to write a small _wrapper_ for the old `v0`-interfaces, but gave up when being confronted with `Hiding` and `Cipher`...

The other, more simple solution, is to ignore `experimental` when testing with travis.

### PR DESCRIPTION
**Pull request by ineiti**
Some cleaning up of our new development model:
- `master/.travis.yml` doesn't need `go_import_path`
- moved directory with information about stable distribution from `utils/stable` to `stable`
- removed stable Makefile and updated stable `travis.yml`
- added `// +build experimental` to the `experimental`-directory
- using `dedis/goveralls -show` to show progress in test

Closes #221

### CODE REVIEW

**Comment by nikkolasg** [comment]
Should the `experimental` folder be tested anyway in master branch ? is it already the case ?

**Comment by ineiti** [comment]
`experimental` does not build, as it depends on `abstract`.

**Comment by ineiti** [comment]
https://github.com/dedis/kyber/issues/221

**Comment by nikkolasg** [comment]
Ok great

**Pull request merged**
