### PR TITLE
Fix build failure on macOS

### PR DESCRIPTION
**Pull request by Zytekaron**
update golang.org/x/sys to v0.5.0 to fix build failure on macos
https://github.com/dedis/kyber/issues/480

### CODE REVIEW

**Comment by pierluca** [comment]
Thank you for your contribution @Zytekaron , please don't forget to sign the CLA above ^

**Comment by ineiti** [comment]
Oups - here goes the very old build system :) I just created #482, which fixes the error. Sorry for that. I propose to merge #482, then rebase this PR on the new `master`.

@pierluca does that sound OK to you?

**Comment by Zytekaron** [comment]
any updates on merging this issue?

**Comment by pierluca** [comment]
Hi @Zytekaron ,
Thank you for the ping. I've approved #482 , which should unblock this as soon as the CI finishes running.
Yours sincerely,
Pierluca

**Comment by pierluca** [comment]
There still seems to be an issue when running `go mod tidy`

**Pull request merged**
