### PR TITLE
Publish proof and shuffle as stable.

### PR DESCRIPTION
**Pull request by jeffallen**
Package shuffle is currently used in PriFi and e-voting, so
they must be stable enough.

Shuffle depends on proof, so it must also be stable.

Also: Slight improvements to proof docs.

### CODE REVIEW

**Comment by ineiti** [comment]
Putting it into WorkInProgress till we have a sign-off on this.

**Comment by ineiti** [comment]
Bryan said he wants to have a code-review on this first. @Daeinar , @nikkolasg , and @lbarman volunteered to do so. But probably only on the 18th of June.

**Comment by ineiti** [comment]
kyber/shuffle/pair.go:240, "mismatched vector lengths".

**Comment by jeffallen** [comment]
A new Kyber is coming in Feb, we might publish it to that.

**Pull request closed without merging**
